# Crear el archivo de la secuencia.
archivo = open("data/4_input_adapters.txt", "w")
linea1 = "ATTCGATTATAAGCTCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATC\n"
linea2 = "ATTCGATTATAAGCACTGATCGATCGATCGATCGATCGATGCTATCGTCGT\n"
linea3 = "ATTCGATTATAAGCATCGATCACGATCTATCGTACGTATGCATATCGATATCGATCGTAGTC \n"
linea4 = "ATTCGATTATAAGCACTATCGATGATCTAGCTACGATCGTAGCTGTA\n"
linea5 = "ATTCGATTATAAGCACTAGCTAGTCTCGATGCATGATCAGCTTAGCTGATGATGCTATGCA\n"
archivo.write(linea1)
archivo.write(linea2)
archivo.write(linea3)
archivo.write(linea4)
archivo.write(linea5)
archivo.close()